server:
  port: 8888
spring:
  application:
    name: Test Final Application
  datasource:
    url: jdbc:mysql://localhost:3306/final_test?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    jpa:
      show-sql: true
      generate-ddl: true