-- MySQL Script generated by MySQL Workbench
-- Tue Jun 14 00:06:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema detective
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema detective
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `detective` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `detective` ;

-- -----------------------------------------------------
-- Table `detective`.`detective_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detective`.`detective_tb` (
  `ID` INT NOT NULL,
  `VERSION` INT NOT NULL,
  `CREATED` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `MODIFIED_AT` VARCHAR(125) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `BADGENUMBER` VARCHAR(125) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `ARMED` TINYINT(1) NOT NULL,
  `USER_NAME` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `FIST_NAME` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `LAST_NAME` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `PASSWORD` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `HIRING_DATE` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `RANK` VARCHAR(125) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `STATUS` VARCHAR(125) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `detective`.`evidence_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detective`.`evidence_tb` (
  `ID` INT NOT NULL,
  `VERSION` INT NOT NULL,
  `CREATED` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `MODIFIED_AT` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `NUMBER` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `ITEAMNAME` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `NOTES` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `ARCHIVED` TINYINT(1) NOT NULL,
  `CRIMINAL_CASE` VARCHAR(125) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `detective`.`criminal_case_tb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detective`.`criminal_case_tb` (
  `ID` INT NOT NULL,
  `VERSION` INT NOT NULL,
  `CREATED` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `MODIFIED_AT` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `NUMBER` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `SHORT_DESCRIPTION` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `DETAILED_DESCRIPTION` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `NOTES` VARCHAR(125) CHARACTER SET 'utf8mb3' NOT NULL,
  `LEAD_INVESTIGATOR` VARCHAR(125) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `detective_tb_ID` INT NOT NULL,
  `evidence_tb_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_criminal_case_tb_detective_tb_idx` (`detective_tb_ID` ASC) VISIBLE,
  INDEX `fk_criminal_case_tb_evidence_tb1_idx` (`evidence_tb_ID` ASC) VISIBLE,
  CONSTRAINT `fk_criminal_case_tb_detective_tb`
    FOREIGN KEY (`detective_tb_ID`)
    REFERENCES `detective`.`detective_tb` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_criminal_case_tb_evidence_tb1`
    FOREIGN KEY (`evidence_tb_ID`)
    REFERENCES `detective`.`evidence_tb` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
